---
# tasks file for ansible-role-nels-galaxy-api
- name: Install and cofigure nels-galaxy software

  block:

    - name: Create nels_galaxy_api group
      group:
        name: "{{nels_galaxy_api_group}}"

    - name: Create nels_galaxy_api user
      user:
        name: "{{nels_galaxy_api_user}}"
        group: "{{nels_galaxy_api_group}}"

    - name: Install Dependencies (for kbr-tools)
      package:
        name:
          - "gcc"
          - "postgresql"
        state: present


    - name: Git checkout of nels-galaxy-api
      git:
        repo: 'https://github.com/usegalaxy-no/nels-galaxy-api.git'
        dest: "{{ nels_galaxy_api_root }}"
        version: master


    - name: create venv in {{ nels_galaxy_api_root }}
      command:
        chdir: "{{  nels_galaxy_api_root }}"
        cmd: python3 -m venv venv
        creates: "{{  nels_galaxy_api_root }}/venv"

    - name: Install specified python requirements for nels-galaxy-api
      pip:
        requirements: "{{  nels_galaxy_api_root }}/requirements.txt"
        virtualenv: "{{  nels_galaxy_api_root }}/venv"

    - name: setup log dir for nels-galaxy-api
      file:
        path: "{{ nels_galaxy_api_log_dir }}"
        state: directory
        owner: "{{nels_galaxy_api_user}}"
        group: "{{nels_galaxy_api_user}}"
        mode: 0755


    - name: Create config file from template
      template:
        src: templates/nga-server.json.j2
        dest: "{{  nels_galaxy_api_root }}/nga-server.json"
        owner: root
        group: root
        mode: '0644'

    - name: copy systemd unit files
      template:
        src: "{{ item.0 }}"
        dest: "{{ item.1 }}"
        owner: root
        group: root
        mode: 0644
        with_together:
          - ['nga-master.systemd.j2', 'nga-runner.systemd.j2']
          - ['/usr/lib/systemd/system/nga-master.service', '/usr/lib/systemd/system/nga-runner\@.service']

    - name: start and enable nga master
      systemd:
        daemon_reload: yes
        start: started
        enabled: yes
        name: nga-master

    - name: start and enable nga runner 1
      systemd:
        daemon_reload: yes
        start: started
        enabled: yes
        name: nga-runner@1

    - name: start and enable nga runner 2
      systemd:
        daemon_reload: yes
        start: started
        enabled: yes
        name: nga-runner@2

