---
# tasks file for ansible-role-tos-api
- name: Install and cofigure ehos-head node

  block:

    - name: Create tos_api group
      user:
        name: "{{tos_api_user}}"

    - name: Create tos_api user
      user:
        name: "{{tos_api_user}}"
        group: "{{tos_api_user}}"

    - name: create {{ tos_api_root }} deployment directory
      file:
        path: "{{ tos_api_root }}"
        state: directory
        owner: "{{ tos_api_user }}"
        group: "{{ tos_api_group }}"
        mode: 0755

    - name: create venv in {{ tos_api_root }}
      become: true
      become_user: "{{ tos_api_user }}"
      command:
        chdir: "{{  tos_api_root }}"
        cmd: python3 -m venv venv
        creates: "{{  tos_api_root }}/venv"


    - name: install tos-api latest
      become: true
      become_user: "{{ tos_api_user }}"
      pip:
        name: git+https://github.com/usegalaxy-no/tos-api.git
        extra_args: --upgrade
        virtualenv: "{{ tos_api_root }}/venv/"
      when: tos_api_version == 'development'

    - name: install tos-api {{tos_api_version }}
      become: true
      become_user: "{{ tos_api_user }}"
      pip:
        name: https://github.com/usegalaxy-no/tos-api/archive/v{{tos_api_version}}.tar.gz
        extra_args: --upgrade
        virtualenv: "{{ tos_api_root }}/venv/"
      when: tos_api_version != 'development'

    - name: setup log dir for tos-api
      file:
        path: "{{ tos_api_log_dir }}"
        state: directory
        owner: "{{tos_api_user}}"
        group: "{{tos_api_user}}"
        mode: 0755

    - name: tos-api systemd file
      template:
        src: "{{tos_api_systemd}}"
        dest: /etc/systemd/system/tos-api.service
      register: tos_api_systemd

    - name: reload tos-api.system file
      systemd:
        state: restarted
        daemon_reload: yes
        name: tos-api
      when: tos_api_systemd.changed

    - name: Make sure tos-api is running
      systemd:
        state: started
        name: tos-api
