---
# tasks file for ansible-role-nels-galaxy-api
- name: Install and cofigure nels-galaxy software

  block:

    - name: Create nels_galaxy_api group
      user:
        name: "{{nels_galaxy_user}}"

    - name: Create nels_galaxy_api user
      user:
        name: "{{nels_galaxy_user}}"
        group: "{{nels_galaxy_user}}"

    - name: create {{ nels_galaxy_api_root }} deployment directory
      file:
        path: "{{ nels_galaxy_api_root }}"
        state: directory
        owner: "{{ nels_galaxy_api_user }}"
        group: "{{ nels_galaxy_api_group }}"
        mode: 0755

    - name: create venv in {{ os_api_root }}
      become: true
      become_user: "{{ nels_galaxy_api_user }}"
      command:
        chdir: "{{  nels_galaxy_api_root }}"
        cmd: python3 -m venv venv
        creates: "{{  nels_galaxy_api_root }}/venv"


    - name: install nels-galaxy-api latest
      become: true
      become_user: "{{ nels_galaxy_api_user }}"
      pip:
        name: git+https://github.com/usegalaxy-no/nels-galaxy-api.git
        extra_args: --upgrade
        virtualenv: "{{ nels_galaxy_api_root }}/venv/"
      when: nels_galaxy_api_version == 'development'

    - name: install nels-galaxy-api {{nels_galaxy_api_version }}
      become: true
      become_user: "{{ nels_galaxy_api_user }}"
      pip:
        name: https://github.com/usegalaxy-no/nels-galaxy-api/archive/v{{nels_galaxy_api_version}}.tar.gz
        extra_args: --upgrade
        virtualenv: "{{ nels_galaxy_api_root }}/venv/"
      when: nels_galaxy_api_version != 'development'

    - name: setup log dir for nels-galaxy-api
      file:
        path: "{{ nels_galaxy_api_log_dir }}"
        state: directory
        owner: "{{nels_galaxy_api_user}}"
        group: "{{nels_galaxy_api_user}}"
        mode: 0755

    - name: nels-galaxy-api systemd file
      template:
        src: "{{nels_galaxy_api_systemd}}"
        dest: /etc/systemd/system/nels-galaxy-api.service
      register: nels_galaxy_api_systemd

    - name: reload nels-galaxy-api.system file
      systemd:
        state: restarted
        daemon_reload: yes
        name: nels-galaxy-api
      when: nels_galaxy_api_systemd.changed

    - name: Make sure nels-galaxy-api is running
      systemd:
        state: started
        name: nels-galaxy-api
