---
# tasks file for ansible-role-nels-galaxy-api
- name: Install and cofigure nels-galaxy software

  block:

    - name: Create nels_galaxy_api group
      group:
        name: "{{nels_galaxy_api_group}}"

    - name: Create nels_galaxy_api user
      user:
        name: "{{nels_galaxy_api_user}}"
        group: "{{nels_galaxy_api_group}}"

    - name: Install Dependencies
      package:
        name:
          - postgresql.x86_64
          - postgresql-devel.x86_64
          - gcc
          - gcc-c++
        state: present


    - name: Git checkout of nels-galaxy-api
      git:
        repo: 'git@git.app.uib.no:cbu-dev/nga.git'
        dest: "{{ nga_root }}"
        force: yes
        version: master


    - name: create venv in {{ nga_root }}
      command:
        chdir: "{{  nga_root }}"
        cmd: python3 -m venv venv
        creates: "{{  nga_root }}/venv"

    - name: Install specified python requirements for nels-galaxy-api
      pip:
        requirements: "{{  nga_root }}/requirements.txt"
        virtualenv: "{{  nga_root }}/venv"

    - name: setup log dir for nels-galaxy-api
      file:
        path: "{{ nels_galaxy_api_log_dir }}"
        state: directory
        owner: "{{nels_galaxy_api_user}}"
        group: "{{nels_galaxy_api_user}}"
        mode: 0755


    - name: Create config file from template
      template:
        src: templates/nga-server.json.j2
        dest: "{{  nga_configdir }}/{{ nels_galaxy_config}}"
        owner: root
        group: root
        mode: '0644'
        backup: True

    - name: copy systemd unit files
      template:
        src: "{{ item.0 }}"
        dest: "{{ item.1 }}"
        owner: root
        group: root
        mode: 0644
      with_together:
        - ['nga-master.systemd.j2']
        - ['/usr/lib/systemd/system/nga-master.service']

    - name: start and enable nga master
      systemd:
        daemon_reload: yes
        state: started
        enabled: yes
        name: nga-master
